apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyecto1-back-ingress
  namespace: press
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: public
  rules:
    - host: 10.43.103.200.nip.io
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: proyecto1
                port:
                  number: 80
